version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: aws-cloudbuild-elasticbeanstalk
  ComputeType: BUILD_GENERAL1_SMALL

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python3.7 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy